name: Build macOS App

on:
  workflow_dispatch:   # 手动触发
  push:
    branches:
      - main           # 或 master，看你用的分支

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller

      - name: Build with PyInstaller
        run: |
          pyinstaller --onefile --windowed main.py
          ls -lh dist/

      - name: Create zip
        run: |
          cd dist
          zip -r MyApp-macOS.zip main.app || true
          zip -r MyApp-macOS-binary.zip main || true
          cd ..

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: MyApp-macOS
          path: dist/*.zip
